# Generated by Django 5.1.6 on 2025-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_somemodel_productmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
